apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true" # enable regex
spec:
  rules:
    - host: ticketing.com # domain name
      http:
        paths:
          - path: /api/users/?(.*) # if this request matches regex...
            pathType: Prefix
            backend:
              service: # ... send request to this service and port
                name: auth-srv
                port:
                  number: 3000
