apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false # true by default
  artifacts:
    - image: cqtan/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync: # copy the matched file to the Pod directly, without rebuild / re-apply Deployment
        manual: # ...this speeds up refresh time when file changes happen
          - src: "src/**/*.js" # ...for any other file not matching: then rebuild and re-apply
            dest: . # Copy destination
    - image: cqtan/comments
      context: comments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: cqtan/event-bus
      context: event-bus
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: cqtan/moderation
      context: moderation
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: cqtan/posts
      context: posts
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: cqtan/query
      context: query
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
